config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'root#index'

  get '/auth/:provider/callback' => 'sessions#create_from_omniauth'


  namespace :api do
    resources :easypost_events, only: %i(create)
    resources :pubsub_messages, only: %i(create)
  end

  namespace :my do
    resource :dashboard, only: %i(show)

    resources :packages, only: %i(new create index show) do
      resource :tracking_refresh, only: %i(create)
      resource :archival, only: %i(create), controller: 'package_archivals'
    end
    resources :push_notification_registrations, only: %i(index create)
  end
end

app/controllers/my/dashboards_controller.rb
# frozen_string_literal: true

module My
  class DashboardsController < ApplicationController
    before_action :require_login

    def show
      @dashboard = DashboardPresenter.new(user: current_user)
    end
  end
end

app/controllers/my/package_archivals_controller.rb
# frozen_string_literal: true

module My
  class PackageArchivalsController < ApplicationController
    def create
      package = current_user.packages.find params[:package_id]
      package.archive!

      redirect_to my_packages_path
    end
  end
end

app/controllers/my/packages_controller.rb
# frozen_string_literal: true

module My
  class PackagesController < ApplicationController
    before_action :require_login

    def new
      @package_creator = PackageCreator.new
    end

    def create
      @package_creator = PackageCreator.new package_creator_params
      if @package_creator.save
        redirect_to my_packages_path
      else
        render :new
      end
    end

    def index
      @show_archived = ActiveRecord::Type::Boolean.new.deserialize(params[:show_archived])

      package_relation = current_user.packages
      package_relation = package_relation.unarchived unless @show_archived
      @packages = package_relation.includes(:newest_tracking_update).sort_by(&:order).reverse
    end

    def show
      @package = current_user.packages.find params[:id]
    end

    private

    def package_creator_params
      params.require(:package_creator).permit(:name, :tracking_number, :carrier_code).merge(user: current_user)
    end
  end
end

app/controllers/my/push_notification_registrations_controller.rb
# frozen_string_literal: true

module My
  class PushNotificationRegistrationsController < ApplicationController
    before_action :require_login

    def index
      @vapid_public_key = Rails.application.secrets.vapid_public_key
    end

    def create
      current_user.push_notification_registrations.find_or_create_by!(registration_params)
    end

    private

    def registration_params
      {
        endpoint: subscription_params[:endpoint],
        p256dh: subscription_params[:keys][:p256dh],
        auth: subscription_params[:keys][:auth]
      }
    end

    def subscription_params
      params.require(:subscription).permit(:endpoint, keys: %i[auth p256dh])
    end
  end
end

app/controllers/my/tracking_refreshes_controller.rb
# frozen_string_literal: true

module My
  class TrackingRefreshesController < ApplicationController
    def create
      package = current_user.packages.find params[:package_id]
      package.refresh_tracking!
      redirect_to my_package_path(package)
    end
  end
end

app/views/my/dashboards/_arriving_today_card.html.erb
<div class="column is-half has-paddding-20">
  <div class="card">
    <header class="card-header">
      <div class="card-header-title is-block">
        <p>
          <%= package.name %> <span class="has-text-weight-normal">- <%= package.tracking_number %></span>
        </p>
        <p class="is-size-7 has-text-weight-normal">
          <%= package.carrier.name %>
        </p>
      </div>
      <span class="card-header-icon has-cursor-default has-text-info" aria-label="package icon">
        <span class="icon is-large">
          <% if package.carrier.icon? %>
            <i class="fab fa-3x fa-<%= package.carrier.fab_icon %>" aria-hidden="true"></i>
          <% else %>
            <i class="far fa-2x fa-box" aria-hidden="true"></i>
          <% end %>
        </span>
      </span>
    </header>
    <footer class="card-footer">
      <div class="card-footer-item is-size-7 flex-column align-items-flex-start">
        <p>
          <%= package.display_status %>
        </p>
        <p>
          <%= package.newest_tracking_update.message %>
        </p>
      </div>
      <div class="card-footer-item is-size-7 flex-column align-items-flex-end">
        <p>Last Updated</p>
        <p><%= package.newest_tracking_update.tracking_updated_at.strftime('%r') %></p>
      </div>
      <%# <a href="#" class="card-footer-item">Delete</a> %>
    </footer>
  </div>
</div>

app/views/my/dashboards/_dashboard.html.erb
<h2 class="subtitle has-text-centered">
  <%= t('dashboard.arriving_today_title', number: dashboard.packages_arriving_today.count) %>
</h2>

<div class="columns is-multiline has-padding-left-20 has-padding-right-20">
  <%= render collection: dashboard.packages_arriving_today, as: :package, partial: 'arriving_today_card' %>
</div>

app/views/my/dashboards/_empty.html.erb
<h2 class="subtitle has-text-centered">
  <%= t('dashboard.empty.title') %>
</h2>

<figure class="image is-square">
  <%= image_tag 'launcher-icon.png' %>
</figure>

app/views/my/dashboards/show.html.erb
<div class="buttons has-addons is-centered">
  <%= link_to new_my_package_path, class: 'button is-rounded is-link' do %>
    <span class="icon">
      <i class="fas fa-plus"></i>
    </span>
    <span><%= t('dashboard.add_button') %></span>
  <% end %>
</div>

<% if @dashboard.empty? %>
  <%= render partial: 'empty', locals: { dashboard: @dashboard } %>
<% else %>
  <%= render partial: 'dashboard', locals: { dashboard: @dashboard } %>
<% end %>