config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'root#index'

  get '/auth/:provider/callback' => 'sessions#create_from_omniauth'


  namespace :api do
    resources :easypost_events, only: %i(create)
    resources :pubsub_messages, only: %i(create)
  end

  namespace :my do
    resource :dashboard, only: %i(show)

    resources :packages, only: %i(new create index show) do
      resource :tracking_refresh, only: %i(create)
      resource :archival, only: %i(create), controller: 'package_archivals'
    end
    resources :push_notification_registrations, only: %i(index create)
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar is-primary" role="navigation" aria-label="main navigation" style="margin-bottom: 10px">
  <div class="navbar-brand">
    <!-- navbar items, navbar burger... -->
    <%= link_to root_url, class: 'navbar-item' do %>
      <figure class="image is-28x28">
        <%= image_tag 'launcher-icon-4x.png' %>
      </figure>
    <% end %>
    <%= link_to root_url, class: 'navbar-item' do %>
      Package Tracker
    <% end %>

    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu" id="navMenu">
    <!-- navbar start, navbar end -->
    <div class="navbar-start">
      <!-- navbar items -->
      <%= link_to 'My Packages', my_packages_path, class: 'navbar-item' %>
    </div>

    <div class="navbar-end">
      <!-- navbar items -->
      <% if signed_in? %>
        <div class="navbar-item">
          Signed in as: <%= current_user.email %>
        </div>
        <div class="navbar-item">
          <%= button_to 'Sign out', sign_out_path, method: :delete, class: 'button' %>
        </div>
      <% else %>
        <div class="navbar-item">
          <%= link_to 'Sign in', sign_in_path, class: 'button' %>
        </div>
      <% end %>
    </div>
  </div>
</nav>